# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 15:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubikPost', '0002_auto_20180125_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
